# Generated by Django 5.0.6 on 2024-08-13 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModelName', models.CharField(default='', max_length=100)),
                ('BImotor', models.CharField(default='', max_length=100)),
                ('Blower', models.CharField(default='', max_length=100)),
                ('FanMotor', models.CharField(default='', max_length=100)),
                ('Eva', models.CharField(default='', max_length=100)),
                ('Fan', models.CharField(default='', max_length=100)),
                ('ConPipe', models.CharField(default='', max_length=100)),
                ('CondCoil', models.CharField(default='', max_length=100)),
                ('RefCharge', models.CharField(default='', max_length=100)),
                ('Capilary', models.CharField(default='', max_length=100)),
                ('Compressor', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('ModelName', models.CharField(max_length=100)),
                ('Date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='TV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('ModelName', models.CharField(max_length=100)),
                ('Date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Washing_Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('ModelName', models.CharField(max_length=100)),
                ('Date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
