# Generated by Django 5.0.6 on 2024-09-06 07:11

import django.db.models.deletion
import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModelName', models.CharField(default='', max_length=100)),
                ('BImotor', models.CharField(default='', max_length=100)),
                ('Blower', models.CharField(default='', max_length=100)),
                ('FanMotor', models.CharField(default='', max_length=100)),
                ('Eva', models.CharField(default='', max_length=100)),
                ('Fan', models.CharField(default='', max_length=100)),
                ('ConPipe', models.CharField(default='', max_length=100)),
                ('CondCoil', models.CharField(default='', max_length=100)),
                ('RefCharge', models.CharField(default='', max_length=100)),
                ('Capilary', models.CharField(default='', max_length=100)),
                ('Compressor', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModelName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModelName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WM_FATL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModelName', models.CharField(default='', max_length=100)),
                ('Type', models.CharField(default='Fully Automatic Top Load Washing Machine', max_length=100)),
                ('RatedCapacity', models.CharField(default='', max_length=100)),
                ('RatedPower', models.CharField(default='', max_length=100)),
                ('RatedSupply', models.CharField(default='', max_length=100)),
                ('RatedFrequency', models.CharField(default='', max_length=100)),
                ('RatedRPM', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Model_Test_Name_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(blank=True, max_length=100, null=True)),
                ('Test_Names', models.JSONField(default=product.models.default_data)),
                ('Test_Count', models.JSONField(default=product.models.default_data)),
                ('Model_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.model_mnf_detail', to_field='Indkal_model_no')),
            ],
        ),
    ]
