# Generated by Django 5.0.6 on 2024-05-31 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('ModelName', models.CharField(max_length=100)),
                ('ProductType', models.CharField(max_length=100)),
            ],
        ),
    ]
