# Generated by Django 5.0.6 on 2024-05-31 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Date',
            field=models.DateField(default=None),
        ),
    ]
