# Generated by Django 5.0.6 on 2024-05-31 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Date',
        ),
    ]
