# Generated by Django 5.0.6 on 2024-05-31 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_ac_delete_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_AC',
        ),
    ]
