# Generated by Django 5.0.6 on 2024-05-31 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0007_delete_product_ac'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_AC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('ModelName', models.CharField(max_length=100)),
            ],
        ),
    ]
