# Generated by Django 5.0.6 on 2024-05-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('ModelName', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Product_AC',
            new_name='AC',
        ),
        migrations.RenameField(
            model_name='ac',
            old_name='ModelName',
            new_name='MoedelName',
        ),
    ]
