# Generated by Django 5.0.6 on 2024-05-31 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_rename_product_ac_ac_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ac',
            old_name='MoedelName',
            new_name='ModelName',
        ),
    ]
