# Generated by Django 5.0.6 on 2024-05-31 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_rename_moedelname_ac_modelname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AC',
            new_name='product_ac',
        ),
    ]
