# Generated by Django 5.0.6 on 2024-05-31 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_rename_ac_product_ac'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product_ac',
            new_name='AC',
        ),
    ]
