# Generated by Django 5.0.6 on 2024-05-31 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_rename_product_ac_ac'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='ac',
            name='Date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
