# Generated by Django 5.0.6 on 2024-05-31 06:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_phone_tv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('ProductType', models.CharField(max_length=100)),
                ('ModelName', models.CharField(max_length=100)),
                ('SerailNo', models.CharField(max_length=100)),
                ('Date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
