# Generated by Django 5.0.6 on 2024-05-31 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_product_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_detail',
            name='Date',
        ),
    ]
