# Generated by Django 5.0.6 on 2024-06-11 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_remove_product_detail_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ac',
            name='Date',
        ),
    ]
