# Generated by Django 5.0.6 on 2024-06-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_remove_ac_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ac',
            name='no',
        ),
        migrations.AddField(
            model_name='ac',
            name='BImotor',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ac',
            name='ModelName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
