# Generated by Django 5.0.6 on 2024-06-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_remove_ac_no_ac_bimotor_alter_ac_modelname'),
    ]

    operations = [
        migrations.AddField(
            model_name='ac',
            name='Blower',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ac',
            name='Capilary',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ac',
            name='ConPipe',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ac',
            name='CondCoil',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ac',
            name='Eva',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ac',
            name='Fan',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ac',
            name='FanMotor',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ac',
            name='RefCharge',
            field=models.CharField(default='', max_length=100),
        ),
    ]
