# Generated by Django 5.0.6 on 2024-06-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_ac_blower_ac_capilary_ac_conpipe_ac_condcoil_ac_eva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ac',
            name='Compressor',
            field=models.CharField(default='', max_length=100),
        ),
    ]
