# Generated by Django 5.0.6 on 2024-06-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_ac_compressor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='TestName',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='product_detail',
            name='TestStage',
            field=models.CharField(default='', max_length=20),
        ),
    ]
