# Generated by Django 5.0.6 on 2024-09-06 07:11

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model_MNF_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.CharField(default='None', max_length=500)),
                ('Manufacture', models.CharField(default='None', max_length=500)),
                ('Location', models.CharField(default='None', max_length=100)),
                ('Brand', models.CharField(default='None', max_length=80)),
                ('Product', models.CharField(default='None', max_length=80)),
                ('Brand_model_no', models.CharField(default='None', max_length=80)),
                ('Indkal_model_no', models.CharField(default='None', max_length=80, unique=True)),
                ('ODM_model_no', models.CharField(default='None', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Test_core_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductType', models.CharField(default='None', max_length=500)),
                ('TestName', models.CharField(default='', max_length=500)),
                ('TestStage', models.CharField(default='', max_length=20)),
                ('Test_Objective', models.CharField(default='', max_length=500)),
                ('Test_Standard', models.CharField(default='', max_length=500)),
                ('Test_Condition', models.TextField(default='', max_length=500)),
                ('Test_Procedure', models.TextField(default='', max_length=700)),
                ('Judgement', models.TextField(default='', max_length=500)),
                ('Instrument', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField(default=datetime.date.today)),
                ('test_start_date', models.DateField(default=datetime.date.today)),
                ('test_end_date', models.DateField(default=datetime.date.today)),
                ('verification', models.BooleanField(default=False)),
                ('sample_quantiy', models.IntegerField(default=0)),
                ('result', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
                ('additional_details', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
                ('employee_remark', models.TextField(blank=True, default='', max_length=500)),
                ('owner_remark', models.TextField(blank=True, default='', max_length=500)),
                ('status', models.CharField(default='Not Sent', max_length=50)),
                ('L_status', models.CharField(default='Not Sent', max_length=50)),
                ('B_status', models.CharField(default='Not Sent', max_length=50)),
                ('ProductType', models.CharField(default='None', max_length=102)),
                ('ModelName', models.CharField(default='None', max_length=100)),
                ('SerailNo', models.CharField(default='None', max_length=100)),
                ('TestStage', models.CharField(default='None', max_length=20)),
                ('TestName', models.CharField(default='None', max_length=80)),
                ('owner_name', models.CharField(default='None', max_length=80)),
            ],
        ),
    ]
