# Generated by Django 5.0.6 on 2024-08-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrecord',
            name='employee_name',
            field=models.CharField(default='None', max_length=80),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='owner_name',
            field=models.CharField(default='None', max_length=80),
        ),
    ]
