# Generated by Django 5.0.6 on 2024-07-05 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model_mnf_detail',
            old_name='Manufature',
            new_name='Manufacture',
        ),
    ]
