# Generated by Django 5.0.6 on 2024-06-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrecord',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
