# Generated by Django 5.0.6 on 2024-06-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrecord',
            name='remark',
        ),
        migrations.AddField(
            model_name='testrecord',
            name='employee_remark',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='owner_remark',
            field=models.CharField(default='None', max_length=500),
        ),
    ]
