# Generated by Django 5.0.6 on 2024-06-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrecord',
            name='ModelName',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='ProductType',
            field=models.CharField(default=' ', max_length=102),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='SerailNo',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='TestName',
            field=models.CharField(default=' ', max_length=80),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='TestStage',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='employee_remark',
            field=models.TextField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='owner_remark',
            field=models.TextField(default=' ', max_length=500),
        ),
    ]
