# Generated by Django 5.0.6 on 2024-06-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_testrecord_remark_testrecord_employee_remark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrecord',
            name='employee_remark',
            field=models.TextField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='owner_remark',
            field=models.TextField(default='None', max_length=500),
        ),
    ]
