# Generated by Django 5.0.6 on 2024-07-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_testrecord_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrecord',
            name='verification',
            field=models.BooleanField(default=False),
        ),
    ]
