# Generated by Django 5.0.6 on 2024-07-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_testrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrecord',
            name='brand_status',
            field=models.CharField(default='Not Send', max_length=80),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='legal_status',
            field=models.CharField(default='Not Send', max_length=80),
        ),
    ]
