# Generated by Django 5.0.6 on 2024-07-04 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_testrecord_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestImage',
        ),
    ]
