# Generated by Django 5.0.6 on 2024-06-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_testrecord_remark_testrecord_employee_remark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrecord',
            name='employee_remark',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='owner_remark',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
    ]
