# Generated by Django 5.0.6 on 2024-06-27 06:57

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_testrecord_remark_testrecord_employee_remark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrecord',
            name='ModelName',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='ProductType',
            field=models.CharField(default='None', max_length=102),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='SerailNo',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='TestName',
            field=models.CharField(default='None', max_length=80),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='TestStage',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='employee_remark',
            field=models.TextField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='notes',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='owner_remark',
            field=models.TextField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='result',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='None'),
        ),
    ]
