# Generated by Django 5.0.6 on 2024-07-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_testrecord_brand_status_testrecord_legal_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrecord',
            name='brand_status',
        ),
        migrations.RemoveField(
            model_name='testrecord',
            name='legal_status',
        ),
        migrations.AddField(
            model_name='testrecord',
            name='B_status',
            field=models.CharField(default='Not Sent', max_length=80),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='L_status',
            field=models.CharField(default='Not Sent', max_length=80),
        ),
    ]
