# Generated by Django 5.0.6 on 2024-06-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_testrecord_modelname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrecord',
            name='notes',
            field=models.CharField(default='', max_length=255),
        ),
    ]
