# Generated by Django 5.0.6 on 2024-07-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_delete_testimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrecord',
            name='B_status',
            field=models.CharField(default='Not sent', max_length=50),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='L_status',
            field=models.CharField(default='Not sent', max_length=50),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='status',
            field=models.CharField(default='Not sent', max_length=50),
        ),
    ]
