# Generated by Django 5.0.6 on 2024-06-11 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_testimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMNFdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.CharField(max_length=500)),
                ('Manufature', models.CharField(max_length=500)),
                ('Location', models.CharField(max_length=100)),
                ('Brand', models.CharField(max_length=80)),
                ('Brand_model_no', models.CharField(max_length=80)),
                ('Indkal_model_no', models.CharField(max_length=80)),
                ('ORM_model_no', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='testrecord',
            name='remark',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='sample_quantiy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='test_end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='test_start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='test_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
