# Generated by Django 5.0.6 on 2024-08-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_testrecord_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrecord',
            name='owner_name',
            field=models.CharField(default='None', max_length=80),
        ),
    ]
