# Generated by Django 5.0.6 on 2024-07-01 05:15

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_testrecord_employee_remark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrecord',
            name='additional_details',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=''),
        ),
    ]
