# Generated by Django 5.0.6 on 2024-07-05 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_testrecord_b_status_testrecord_l_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TestStageDetail',
        ),
    ]
