# Generated by Django 5.0.6 on 2024-06-11 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_modelmnfdetail_testrecord_remark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrecord',
            name='mnfDetail',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='test_mnf_detail', to='employee.modelmnfdetail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modelmnfdetail',
            name='Brand',
            field=models.CharField(default='None', max_length=80),
        ),
        migrations.AlterField(
            model_name='modelmnfdetail',
            name='Brand_model_no',
            field=models.CharField(default='None', max_length=80),
        ),
        migrations.AlterField(
            model_name='modelmnfdetail',
            name='Customer',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='modelmnfdetail',
            name='Indkal_model_no',
            field=models.CharField(default='None', max_length=80),
        ),
        migrations.AlterField(
            model_name='modelmnfdetail',
            name='Location',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='modelmnfdetail',
            name='Manufature',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='modelmnfdetail',
            name='ORM_model_no',
            field=models.CharField(default='None', max_length=80),
        ),
    ]
