# Generated by Django 5.0.6 on 2024-07-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_remove_testrecord_brand_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_core_detail',
            name='ProductType',
            field=models.CharField(default='None', max_length=102),
        ),
    ]
