# Generated by Django 5.0.6 on 2024-07-01 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_testrecord_modelname_and_more'),
        ('employee', '0004_testrecord_additional_details'),
    ]

    operations = [
    ]
