# Generated by Django 5.0.6 on 2024-07-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_delete_test_delete_teststagedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_core_detail',
            name='ProductType',
            field=models.CharField(default='None', max_length=500),
        ),
    ]
