# Generated by Django 5.0.6 on 2024-06-11 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_testrecord_mnfdetail_alter_modelmnfdetail_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrecord',
            name='mnfDetail',
        ),
    ]
