# Generated by Django 5.0.6 on 2024-07-01 07:50

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_merge_20240701_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrecord',
            name='employee_remark',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='owner_remark',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='result',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=''),
        ),
    ]
