# Generated by Django 5.0.6 on 2024-07-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_test_core_detail_producttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrecord',
            name='status',
            field=models.CharField(default='Not Sent', max_length=80),
        ),
    ]
