# Generated by Django 5.0.6 on 2024-07-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_test_core_detail_producttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrecord',
            name='B_status',
            field=models.CharField(default='Not Sent', max_length=50),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='L_status',
            field=models.CharField(default='Not Sent', max_length=50),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='status',
            field=models.CharField(default='Not Sent', max_length=50),
        ),
    ]
