# Generated by Django 5.0.6 on 2024-06-11 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_remove_testrecord_mnfdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_core_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TestName', models.CharField(default='None', max_length=500)),
                ('Test_Objective', models.CharField(default='None', max_length=500)),
                ('Test_Standard', models.CharField(default='None', max_length=500)),
                ('Test_Condition', models.CharField(default='None', max_length=500)),
                ('Test_Procedure', models.CharField(default='None', max_length=500)),
                ('Judgement', models.CharField(default='None', max_length=500)),
                ('Instrument', models.CharField(default='None', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TestStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModelName', models.CharField(default='None', max_length=80)),
                ('TestStage', models.CharField(default='None', max_length=20)),
                ('Test_Report_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
