# Generated by Django 5.0.6 on 2024-07-02 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_testrecord_employee_remark_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model_mnf_detail',
            old_name='Manufature',
            new_name='Manufacture',
        ),
        migrations.RenameField(
            model_name='model_mnf_detail',
            old_name='ORM_model_no',
            new_name='ODM_model_no',
        ),
    ]
