# Generated by Django 5.0.6 on 2024-06-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_test_core_detail_teststage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TestStage', models.CharField(default='None', max_length=20)),
                ('Product', models.CharField(default='None', max_length=35)),
                ('TestName', models.CharField(default='None', max_length=80)),
            ],
        ),
        migrations.RenameModel(
            old_name='TestStage',
            new_name='TestStageDetail',
        ),
    ]
