# Generated by Django 5.0.6 on 2024-06-11 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_testlist_rename_teststage_teststagedetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelMNFdetail',
            new_name='Model_MNF_detail',
        ),
    ]
