# Generated by Django 5.0.6 on 2024-06-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_rename_modelmnfdetail_model_mnf_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_core_detail',
            name='Test_Procedure',
            field=models.TextField(default='None', max_length=500),
        ),
    ]
