# Generated by Django 5.0.6 on 2024-06-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_rename_modelmnfdetail_model_mnf_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_mnf_detail',
            name='Product',
            field=models.CharField(default='None', max_length=80),
        ),
    ]
