# Generated by Django 5.0.6 on 2024-06-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_model_mnf_detail_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_mnf_detail',
            name='Product',
        ),
        migrations.AlterField(
            model_name='test_core_detail',
            name='Judgement',
            field=models.TextField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='test_core_detail',
            name='Test_Condition',
            field=models.TextField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='test_core_detail',
            name='Test_Procedure',
            field=models.TextField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='notes',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='result',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
