# Generated by Django 5.0.6 on 2024-06-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_alter_test_core_detail_test_procedure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_core_detail',
            name='Judgement',
            field=models.TextField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='test_core_detail',
            name='Test_Condition',
            field=models.TextField(default='None', max_length=500),
        ),
    ]
