# Generated by Django 5.0.6 on 2024-06-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_remove_model_mnf_detail_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_mnf_detail',
            name='Product',
            field=models.CharField(default='None', max_length=80),
        ),
        migrations.AlterField(
            model_name='test_core_detail',
            name='Instrument',
            field=models.TextField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='test_core_detail',
            name='Test_Objective',
            field=models.TextField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='test_core_detail',
            name='Test_Standard',
            field=models.TextField(default='None', max_length=500),
        ),
    ]
