# Generated by Django 5.0.6 on 2024-06-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_alter_test_core_detail_judgement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrecord',
            name='notes',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
