# Generated by Django 5.0.6 on 2024-06-18 07:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_model_mnf_detail_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RTF_Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Field1', models.CharField(default='', max_length=50)),
                ('Field2', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
