# Generated by Django 5.0.6 on 2024-06-18 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_model_mnf_detail_product'),
        ('employee', '0012_alter_testrecord_notes'),
    ]

    operations = [
    ]
