# Generated by Django 5.0.6 on 2024-06-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_merge_20240618_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrecord',
            name='ModelName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='ProductType',
            field=models.CharField(default='', max_length=102),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='SerailNo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='TestName',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='TestStage',
            field=models.CharField(default='', max_length=20),
        ),
    ]
