# Generated by Django 5.0.6 on 2024-06-18 09:08

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_rtf_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtf_test',
            name='Field2',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
