# Generated by Django 5.0.6 on 2024-06-19 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_alter_testrecord_notes'),
        ('employee', '0014_alter_rtf_test_field2'),
    ]

    operations = [
    ]
