# Generated by Django 5.0.6 on 2024-06-18 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_testrecord_modelname_testrecord_producttype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrecord',
            name='employee',
        ),
    ]
