# Generated by Django 5.0.6 on 2024-06-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_remove_testrecord_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrecord',
            name='employee',
            field=models.CharField(default='None', max_length=80),
        ),
    ]
