# Generated by Django 5.0.6 on 2024-06-19 06:24

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_merge_20240619_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrecord',
            name='test_name',
        ),
        migrations.AddField(
            model_name='testrecord',
            name='ModelName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='ProductType',
            field=models.CharField(default='', max_length=102),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='SerailNo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='TestName',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='TestStage',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='rtf_test',
            name='Field2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test_core_detail',
            name='Instrument',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='test_core_detail',
            name='Test_Objective',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='test_core_detail',
            name='Test_Standard',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='employee',
            field=models.CharField(default='None', max_length=80),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='result',
            field=models.CharField(max_length=255),
        ),
    ]
