# Generated by Django 5.0.6 on 2024-06-19 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_remove_testrecord_test_name_testrecord_modelname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testrecord',
            old_name='sample_quantiy',
            new_name='sample_quantity',
        ),
    ]
