# Generated by Django 5.0.6 on 2024-06-19 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_testrecord_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrecord',
            name='test_name',
        ),
    ]
