# Generated by Django 5.0.6 on 2024-06-19 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_alter_rtf_test_field2'),
        ('employee', '0017_remove_testrecord_test_name'),
    ]

    operations = [
    ]
