# Generated by Django 5.0.6 on 2024-06-19 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_merge_20240619_1215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RTF_Test',
        ),
    ]
