# Generated by Django 5.0.6 on 2024-06-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user_type',
            field=models.CharField(default='yami', max_length=50),
            preserve_default=False,
        ),
    ]
