# Generated by Django 5.0.6 on 2024-07-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user_type',
            field=models.CharField(blank=True, choices=[('employee', 'Employee'), ('owner', 'Owner'), ('legal', 'Legal'), ('brand', 'Brand')], max_length=50),
        ),
    ]
