# Generated by Django 5.0.6 on 2024-07-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_employee_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user_type',
            field=models.CharField(choices=[('employee', 'Employee'), ('owner', 'Owner'), ('legal', 'Legal'), ('brand', 'Brand')], max_length=50, null=True),
        ),
    ]
