# Generated by Django 5.0.6 on 2024-06-13 09:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_employee_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_login',
            field=models.TimeField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
