# Generated by Django 5.0.6 on 2024-06-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_employee_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='last_login',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
