# Generated by Django 5.0.6 on 2024-07-15 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_employee_options_alter_employee_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AlterModelManagers(
            name='employee',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user_permissions',
        ),
    ]
